// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu0mO8KSaddoTIz2utV2lFi8xmP0JEPyY',
    appId: '1:229187536472:web:2d8db50f5755586dfa2c2d',
    messagingSenderId: '229187536472',
    projectId: 'rika-store-dffc7',
    authDomain: 'rika-store-dffc7.firebaseapp.com',
    storageBucket: 'rika-store-dffc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhIl_2ZLcjMm9Go6PO2iNI0iU9frIISug',
    appId: '1:229187536472:android:c22c8898a8b62203fa2c2d',
    messagingSenderId: '229187536472',
    projectId: 'rika-store-dffc7',
    storageBucket: 'rika-store-dffc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSuXcDRznHzC1RWSxdxMgym-e8y2Gi4c',
    appId: '1:229187536472:ios:48b48299fcdd24f3fa2c2d',
    messagingSenderId: '229187536472',
    projectId: 'rika-store-dffc7',
    storageBucket: 'rika-store-dffc7.firebasestorage.app',
    iosBundleId: 'com.example.rikaStore',
  );

}